### ISSUE TITLE
Making the Library Slightly more Robust?

### ISSUE THREAD

**Issue by frastlin** [Ghorthalon/agk-tts#2]
Hello,
Sorry these are not split into different issues. Our team wants to start contributing to this to do the following. Please let me know your thoughts (I'm using this as a task list):

1. [ ] Allow us to register a custom component that can show text that is being spoken visually.
2. [ ] There should be a way to force tts or screen reader with the speak function. Sometimes I will want to send a particular message through TTS, especially if holding down the arrow keys and I want a message to play.
3. [ ] The default element (this.aria) should have the attribute aria-atomic="true".
4. [x] Create a stop method for the web TTS that doesn't error when there is screen reader or no speech.
5. [ ] Have a promise for the web TTS that resolves when the speech finishes. The screen reader won't have a time, but maybe there can be a number of time that can be passed to speak to wait for the promise if it's a screen reader.
6. [ ] Have a way to easily configure and access web TTS options through functions.
7. [ ] Have an HTML element that can be used to configure the text to speech.
8. [ ] Allow a JSON config to be exported of the current settings, and allow a JSON config to be loaded again with settings.
9. [ ] Allow the default method of speech to be toggled between screen reader and text to speech with a method.

**Comment by Ghorthalon** [comment]
Hey @frastlin 

You can go right ahead and make those changes.
My plan for this library however is to eventually sunset it. Right now, I'm working on a replacement for all the AGK-libraries. My plan is to bundle them all into one audiogame-tools repository which includes:
* Asset management (loading big sound files, storing them locally in the browser cache or a directory, manifests to update sounds as they change)
* Entity Component System library: Entities are things in your game. Components are the data for Entities, and Systems iterate over specific entities with certain components to execute code. For example, a player entity would contain a position component (x, y, z), a health component (hp) and a velocity component (x, y, z). Then you could have a movement system which iterates over every single entity which has a movement and velocity component and update it accordingly.
* A simple event bus
* A completely rewritten input system which can take advantage of controllers, mouse, keyboard, and pointer lock
* Some commonly used math functions
* Extremely basic 3d physics
* A wrapper around WebAudio designed for games with static and streaming sources, and very easdy way to load a convolution reverb for different environments
* A scene manager to easily switch between different views or screens of your game and pass data between them
* A very basic scheduler
* The new and completely rewritten TTS module
* A new and completely rewritten UI module

The project is written in TypeScript and currently hosted on my personal Git server, however seeing that you have interest in this library, I can move it over to GitHub so you can make changes to it instead. I would much prefer that, since I completely reworked the architecture using everything I've learned making games over the past couple years.

If you'd like to keep using this library, you can of course feel free to make pull requests and I will merge them in and update it on NPM. But if you're at all curious or willing to switch to the new library, please let me know.

**Comment by frastlin** [comment]
I would love to see the new library! What of these features does the new library support already?

**Comment by frastlin** [comment]
Closing in favor of:
https://github.com/Ghorthalon/audiogame-tools/issues/1
